[build-system]
dependencies = ["pillow==10.3.0"]

[project]
name = "gifanimus"
authors = [{name = "Fibo Metavinci", email = "pszdw-75nat-5227i-bha5s-y7lai-pebdq-o2agp-3xho4-hd6z6-emxrd-nqe@dmail.ai"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/inviti8"
